/// ZKRangeProofVerifier — Production IProofVerifier implementation
///
/// Wraps the Garaga-generated UltraKeccakZKHonk verifier for the ShieldedBTC range proof circuit.
///
/// Circuit semantics (Noir, BN254 field):
///   Private: amount (u64, satoshis), secret (Field)
///   Public:  commitment = poseidon2([amount, secret, 0, 0], t=4)[0]
///            threshold (u64, satoshis)
///
///   Constraints:
///     poseidon2([amount, secret, 0, 0], 4)[0] == commitment
///     amount > threshold
///
/// The verifier receives `full_proof_with_hints` (calldata generated by the Garaga npm SDK),
/// passes it to the Garaga-generated verifier, and checks that the returned public inputs
/// match the `commitment` (from on-chain storage) and `threshold` provided by the caller.
///
/// Replaces StubProofVerifier. Upgrade path: vault.set_verifier(this_address).
#[starknet::contract]
pub mod ZKRangeProofVerifier {
    use core::array::{Span, SpanTrait};
    use shielded_btc_collateral::contracts::honk_verifier::honk_verifier::{
        IUltraKeccakZKHonkVerifierDispatcher, IUltraKeccakZKHonkVerifierDispatcherTrait,
    };
    use shielded_btc_collateral::interfaces::iproof_verifier::IProofVerifier;
    use starknet::ContractAddress;
    use starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};

    // =========================================================================
    // Storage
    // =========================================================================

    #[storage]
    struct Storage {
        /// Address of the deployed Garaga-generated HonkVerifier contract.
        honk_verifier: ContractAddress,
        /// Owner — can update the honk_verifier address.
        owner: ContractAddress,
    }

    // =========================================================================
    // Events
    // =========================================================================

    #[event]
    #[derive(Drop, starknet::Event)]
    pub enum Event {
        HonkVerifierUpdated: HonkVerifierUpdated,
    }

    #[derive(Drop, starknet::Event)]
    pub struct HonkVerifierUpdated {
        pub previous: ContractAddress,
        pub updated: ContractAddress,
    }

    // =========================================================================
    // Constructor
    // =========================================================================

    #[constructor]
    fn constructor(
        ref self: ContractState,
        honk_verifier: ContractAddress,
        owner: ContractAddress,
    ) {
        let zero: ContractAddress = 0.try_into().unwrap();
        assert(honk_verifier != zero, 'HonkVerifier cannot be zero');
        assert(owner != zero, 'Owner cannot be zero');
        self.honk_verifier.write(honk_verifier);
        self.owner.write(owner);
    }

    // =========================================================================
    // IProofVerifier implementation
    // =========================================================================

    #[abi(embed_v0)]
    impl ZKRangeProofVerifierImpl of IProofVerifier<ContractState> {
        /// Verify a ZK range proof generated by the Noir circuit.
        ///
        /// `commitment`: The BN254 Poseidon2 commitment stored on-chain for this user.
        ///              (poseidon2([amount, secret, 0, 0], t=4)[0])
        /// `threshold`:  Minimum required amount in satoshis.
        /// `proof`:      Full proof with hints generated by the Garaga npm SDK.
        ///              (garaga.getZKHonkCallData(...))
        ///
        /// Returns true iff:
        ///   1. The Honk proof verifies correctly.
        ///   2. Public input[0] (commitment in proof) == provided `commitment`.
        ///   3. Public input[1] (threshold in proof) matches provided `threshold`.
        fn verify_range_proof(
            self: @ContractState,
            commitment: felt252,
            threshold: u256,
            proof: Span<felt252>,
        ) -> bool {
            // Proof must be non-empty for the ZK verifier.
            if proof.is_empty() {
                return false;
            }

            let honk_verifier_addr = self.honk_verifier.read();
            let zero: ContractAddress = 0.try_into().unwrap();
            if honk_verifier_addr == zero {
                return false;
            }

            let honk = IUltraKeccakZKHonkVerifierDispatcher {
                contract_address: honk_verifier_addr,
            };

            // Call the Garaga-generated verifier.
            // Returns Ok(public_inputs: Span<u256>) on success, Err on failure.
            let result = honk.verify_ultra_keccak_zk_honk_proof(proof);

            match result {
                Result::Err(_) => false,
                Result::Ok(public_inputs) => {
                    // Circuit public inputs order (matches main.nr fn signature):
                    //   [0] commitment  (BN254 Field → u256)
                    //   [1] threshold   (u64 → u256)
                    let inputs: Span<u256> = public_inputs;
                    if SpanTrait::len(inputs) < 2 {
                        return false;
                    }

                    // Extract public input[0]: BN254 commitment from the proof
                    let proof_commitment_u256 = *SpanTrait::at(inputs, 0);

                    // Convert the on-chain felt252 commitment to u256 for comparison.
                    let commitment_as_u256: u256 = commitment.into();

                    // Extract public input[1]: threshold from the proof
                    let proof_threshold_u256 = *SpanTrait::at(inputs, 1);

                    // Both must match what was provided by the caller.
                    proof_commitment_u256 == commitment_as_u256
                        && proof_threshold_u256 == threshold
                },
            }
        }
    }

    // =========================================================================
    // Admin
    // =========================================================================

    #[generate_trait]
    impl AdminImpl of AdminTrait {
        /// Update the Garaga HonkVerifier contract address (e.g., after a circuit upgrade).
        fn set_honk_verifier(ref self: ContractState, new_honk_verifier: ContractAddress) {
            assert(
                starknet::get_caller_address() == self.owner.read(), 'Only owner',
            );
            let prev = self.honk_verifier.read();
            self.honk_verifier.write(new_honk_verifier);
            self.emit(HonkVerifierUpdated { previous: prev, updated: new_honk_verifier });
        }
    }
}
